---
- name: assure ufw installed
  apt: pkg=ufw state=present

- name: enable ufw service at boot
  service: name=ufw enabled=True

# - name: setup kernel tracking
# lineinfile:
#   dest: /etc/default/ufw
#   regexp: '^IPT_MODULES='
#   line: 'IPT_MODULES="{{ ufw_kernel }}"'
#   state: present

- name: update sysctl forward ipv4
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes

- name: update sysctl forward ipv6
  sysctl: name="net.ipv6.conf.all.forwarding" value=1 sysctl_set=yes

- name: enable ssh (always)
  ufw: rule=allow name=OpenSSH
  notify:
    - reload ufw

