---
- name: assure ufw installed
  apt: pkg=ufw state=present

# - name: setup kernel tracking
# lineinfile:
#   dest: /etc/default/ufw
#   regexp: '^IPT_MODULES='
#   line: 'IPT_MODULES="{{ ufw_kernel }}"'
#   state: present

- name: update sysctl forward ipv4
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes

- name: update sysctl forward ipv6
  sysctl: name="net.ipv6.conf.all.forwarding" value=1 sysctl_set=yes

- name: UFW Default config - INPUT_POLICY Drop
  lineinfile: 
    dest: /etc/default/ufw
    regexp: "^DEFAULT_INPUT_POLICY"
    line: 'DEFAULT_INPUT_POLICY="DROP"'
  notify:
    - reload ufw

- name: UFW Default config - FORWARD_POLICY Drop
  lineinfile:
    dest: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY"
    line: 'DEFAULT_FORWARD_POLICY="DROP"'
  notify:
    - reload ufw


- name: enable ssh (always)
  ufw: rule=allow name=OpenSSH
  notify:
    - reload ufw


