#-A INPUT -i eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
#-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
#-A INPUT -p tcp -m tcp --dport 45103 -j ACCEPT
#-A INPUT -i tun0 -j ACCEPT
#-A FORWARD -d 10.0.10.10/32 -i eth0 -o br0 -p tcp -m tcp --dport 51001 -j ACCEPT
#-A POSTROUTING -s 10.0.10.5/32 -o eth0 -j SNAT --to-source 91.134.50.213
#-A POSTROUTING -o eth0 -j MASQUERADE


#-A PREROUTING -d 149.202.65.131 -i eth0 -p tcp -m tcp --dport 51001 -j DNAT --to-destination 10.0.10.12:22
---
- debug: var=ufw.forwarding

- name: Define variables 
  set_fact: 
    before_rules: []
    nat_rules: []

- include: 'rules/port_forwarding.yml' 
  with_subelements:
    - "{{ ufw.forwarding }}"
    - forwards 
  when: forwards is not none

- include: 'rules/reroute.yml'
  with_subelements:
    - "{{ ufw.forwarding }}"
    - reroute

- include: 'rules/forwarding.yml'
  with_items:
    - "{{ ufw.forwarding }}"

- debug: var=before_rules
- debug: var=nat_rules
#
#- name: configure iptables masquerading
#  template: src=ufw/before.rules.j2 dest=/etc/ufw/before.rules mode=0644
#  notify:
#    - restart ufw
#
#- name: configure ip6tables rules 
#  template: src=ufw/before6.rules.j2 dest=/etc/ufw/before6.rules mode=0644
#  notify:
#    - restart ufw
