---
- debug: var=item
- block:
  - name: Create iptables POSTROUTING array
    set_fact: iptables_command="[ '-A', 'PREROUTING' ]"

  - name: Add incomming_dev rule
    set_fact: iptables_command="{{ iptables_command }} + [ '-i', '{{ item.0.incomming_dev }}' ]"
  
  - name: Add incomming_dev rule
    set_fact: iptables_command="{{ iptables_command }} + [ '-d', '{{ item.1.incomming_ip }}' ]"

  - name: Add SNAT 
    set_fact: iptables_command="{{ iptables_command }} + [ '-j', 'DNAT' ]"

  - name: Add to-source rule 
    set_fact: iptables_command="{{ iptables_command }} + [ '--to-destination', '{{ item.1.destination_ip }}:{{ item.1.destination_port }}' ]"

  - name: Add set protocols 
    set_fact: 
      nat_rules: "{{ nat_rules }} + [ {{ iptables_command }} + [ '-p', '{{ item }}', '-m', '{{ item }}' ]]"
    with_items: "{{ item.1.protocols }}"


